=== StephenElmer/starthrower-utilities/Samples/Languages/grammar.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:annotation>
        <xsd:documentation xml:lang="en">
            Grammar definition for Pep.
            Copyright (C) 2007 Scott Martin
            Author: Scott Martin (http://www.ling.osu.edu/~scott/)
            $Id: grammar.xsd 1812 2010-02-08 22:06:32Z scott $

            This library is free software; you can redistribute it and/or modify it
            under the terms of the GNU Lesser General Public License as published by
            the Free Software Foundation; either version 2.1 of the License, or (at
            your option) any later version. The GNU Lesser General Public License is
            distributed with this software in the file COPYING.
        </xsd:documentation>
    </xsd:annotation>

    <xsd:element name="grammar" type="grammarType"/>

    <xsd:complexType name="grammarType">
        <xsd:sequence>
            <xsd:element name="rule" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:ID" use="required"/>
    </xsd:complexType>

    <xsd:element name="rule" type="ruleType"/>

    <xsd:complexType name="ruleType">
        <xsd:sequence>
            <xsd:element name="category" minOccurs="1" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:attribute name="name" type="xsd:NMTOKEN" use="required"/>
                    <xsd:attribute name="terminal" default="false">
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:enumeration value="true"/>
                                <xsd:enumeration value="false"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:attribute>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="category" type="xsd:NMTOKEN" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== StephenElmer/starthrower-utilities/Samples/Languages/mylanguage.xml
<?xml version="1.0"?>
<grammar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="grammar.xsd" name="MyGrammar">
    
    <rule category="S">
        <category name="NExp"/>
    </rule>
    
    <rule category="NExp">
        <category name="Add"/>
    </rule>
    <rule category="NExp">
        <category name="Sub"/>
    </rule>
    <rule category="NExp">
        <category name="Num"/>
    </rule>

    <rule category="Add">
        <category name="NExp"/>
        <category terminal="true" name="+"/>
        <category name="NExp"/>
    </rule>

    <rule category="Sub">
        <category name="NExp"/>
        <category terminal="true" name="-"/>
        <category name="NExp"/>
    </rule>
    
    <rule category="Num">
        <category terminal="true" name="3"/>
    </rule>
    <rule category="Num">
        <category terminal="true" name="5"/>
    </rule>

</grammar>

=== StephenElmer/starthrower-utilities/Samples/Languages/earley.xml
<?xml version="1.0"?>
<grammar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="grammar.xsd" name="Earley">
    
    <rule category="S">
        <category name="E"/>
    </rule>

    <rule category="E">
        <category name="T"/>
    </rule>
    <rule category="E">
        <category name="E"/>
        <category terminal="true" name="+"/>
        <category name="T"/>
    </rule>

    <rule category="T">
        <category name="p"/>
    </rule>
    <rule category="T">
        <category name="T"/>
        <category terminal="true" name="*"/>
        <category name="p"/>
    </rule>

    <rule category="p">
        <category terminal="true" name="a"/>
    </rule>

</grammar>

=== StephenElmer/starthrower-utilities/Samples/Languages/earley2.xml
<?xml version="1.0"?>
<grammar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="grammar.xsd" name="Earley">
    
    <rule category="S">
        <category name="E"/>
    </rule>

    <rule category="E">
        <category name="T"/>
    </rule>
    <rule category="E">
        <category name="E"/>
        <category name="plus"/>
        <category name="T"/>
    </rule>

    <rule category="T">
        <category name="p"/>
    </rule>
    <rule category="T">
        <category name="T"/>
        <category name="times"/>
        <category name="p"/>
    </rule>

    <rule category="p">
        <category terminal="true" name="a"/>
    </rule>

    <rule category="times">
        <category terminal="true" name="*"/>
    </rule>

    <rule category="plus">
        <category terminal="true" name="+"/>
    </rule>
    
</grammar>
